name: Test / Build / Publish

on:
  push:
    tags: ['v*']     # push a tag like `v1.2.3` to publish to PyPI
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Manual runs will publish to PyPI by default
    inputs: {}

jobs:
  test-and-build:
    name: Run tests and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml', '**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install build & test deps
        run: |
          python -m pip install --upgrade pip
          pip install build twine pytest

      - name: Install package (editable) with crosshair extra
        run: |
          # Make the local package importable for tests and install optional crosshair tooling
          python -m pip install -e ".[crosshair]"

      - name: Run tests
        run: pytest -q

      - name: Build distributions
        run: python -m build --sdist --wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    needs: test-and-build
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1